### ISSUE TITLE
Installing python packages

### ISSUE THREAD

**Issue by cdesch** [trashgenerator/motoparking#98]
I recieve this error when running `pip install -r requirements.txt` command

```
Collecting flask-social-blueprint==0.7 (from -r requirements.txt (line 35))
  Using cached https://files.pythonhosted.org/packages/50/c0/44b61ea045cd7a6d7ac315f41cdaa60ec1b88184f90fef8586d214130962/flask-social-blueprint-0.7.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cb/_4gwm8d117n47dwx_k2jqkg80000gn/T/pip-install-a0q0Rz/flask-social-blueprint/setup.py", line 7, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cb/_4gwm8d117n47dwx_k2jqkg80000gn/T/pip-install-a0q0Rz/flask-social-blueprint/
```

**Comment by cdesch** [comment]
This [Commit](https://github.com/wooyek/flask-social-blueprint/commit/cc27b71c90e74e45afbf7586de7694cf7691628e) fixed it in [flask-social-blueprint](https://github.com/wooyek/flask-social-blueprint)

Change the requirements.txt to the following until they release a `0.7.3` with the changes merged.

`git+git://github.com/wooyek/flask-social-blueprint@develop#flask-social-blueprint`

**Comment by nosovsh** [comment]
Thanks!
